version: '3.5'

services:

    #HoneyGain Configuration
    honeygain:
        image: honeygain/honeygain
        platform: linux/amd64
        command: -tou-accept -email 'harrypoterbaoboituthan@gmail.com' -pass 'Anhbeos123@' -device EarningMachine
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.106.0.20
    #end of HoneyGain Configuration

    #TraffMonetizer Configuration
    traffmonetizer:
        image: traffmonetizer/cli_v2:arm64v8
        restart: unless-stopped
        command: start accept --token X1fXYApdNEfkdO73FhtZUYGOIny0h8+xt0GjTi47dLw=
        networks:
            default:
                ipv4_address: 172.106.0.30
    #end of TraffMonetizer Configuration

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.106.0.0/16
